# Generated by Django 3.2 on 2021-11-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_details_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='avatar',
            field=models.ImageField(upload_to='cities'),
        ),
    ]
